name: Run Pytest Selenium (Manual Only)

on:
  workflow_dispatch:  # 手動觸發，不自動跑

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
        options: >-
          --shm-size=2g
          --health-cmd="curl -f http://localhost:4444 || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pytest
        env:
          SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub
        run: pytest test_login.py -v